Repository MrMoon/Vision, pull requests merged in 2021-03, with the labels that each got.

#1 Create a README
  README.md
Labels: documentation

#2 Update README
  README.md
Labels: documentation

#3 commit
  .gitignore
Labels: documentation

#4 Models
  Models/SystemContextViewDiagram.drawio
Labels: documentation

#6 Update README
  README.md
Labels: documentation

#7 Added Research Papers
  README.md
Labels: documentation

#11 Lecture review
  Models/Screenshot from 2021-03-04 21-40-51.png
  Models/SystemContextViewDiagram.png
  README.md
Labels: documentation

#13 Vision Projection - Gantt Chart
  Models/GanttChart.pdf
  Models/VisionGanttChart.png
  Pictures/GlassesBlur.jpg
  README.md
Labels: documentation

#14 Fix README pictures
  README.md
Labels: bug

#16 Network Diagram
  Models/NetworkDiagram.drawio
  Models/NetworkDiagram.png
  README.md
Labels: documentation

#18 Fix and Clean
  README.md
Labels: documentation

#19 Fix and Clean README
  Models/Drawing/NetworkDiagram.drawio
  Models/Drawing/SystemContextViewDiagram.drawio
  Models/GanttChart.pdf
  Models/SystemContextViewDiagram.png
  Pictures/GlassesBlur.jpg
  README.md
Labels: documentation

#20 update headlines
  README.md
Labels: documentation

#22 commit fix and clean
  README.md
Labels: documentation

#26 Phase One final
  Documents/Phase/Vision Phase One.pdf
Labels: documentation

#27 Phase Two GanttChart
  Models/VisionPhase2GanttChart.png
  README.md
Labels: documentation

#28 update vision gantt chart
  Models/VisionPhase2GanttChart.png
Labels: documentation

#29 update README
  README.md
Labels: documentation

#30 Update Headlines
  Models/VisionPhase2GanttChart.png
Labels: documentation

#31 update readme headlines
  README.md
Labels: documentation

#32 remove headlines
  README.md
Labels: documentation

#33 update project documentation
  README.md
Labels: documentation

#34 update project documentation link
  README.md
Labels: documentation

#39 Activity Diagram
  Models/Drawing/ActivityDiagram.drawio
Labels: documentation

#43 Math Models
  Models/BasicImageDegradationModel.png
  Models/Drawing/BasicImageDegradationModel.drawio
Labels: documentation

#42 Activity Diagram Image
  Models/ActivityDiagram.png
Labels: documentation

#45 Re-arrange model files and directories
  Models/drawing/ActivityDiagram.drawio
  Models/drawing/BasicImageDegradationModel.drawio
  Models/drawing/NetworkDiagram.drawio
  Models/drawing/SystemContextViewDiagram.drawio
  Models/imgs/ActivityDiagram.png
  Models/imgs/BasicImageDegradationModel.png
  Models/imgs/NetworkDiagram.png
  Models/imgs/SystemContextViewDiagram.png
  Models/imgs/VisionGanttChart.png
  Models/imgs/VisionPhase2GanttChart.png
Labels: documentation

#46 Gantt Chart
  Models/imgs/VisionGanttChart.png
Labels: bug, documentation

#49 Class Diagram
  Models/drawing/ClassDiagram.drawio
  Models/imgs/ClassDiagram.png
Labels: documentation

#50 update project docs link
  README.md
Labels: documentation

#52 Updated Network Diagram
  Models/drawing/NetworkDiagram.drawio
  Models/imgs/VisionGanttChart.png
Labels: documentation, drawing

#53 Update Network Diagram Image
  Models/imgs/NetworkDiagram.png
Labels: documentation

#54 Added Phase Two Document
  Documents/Phases/One/Vision Phase One.pdf
  Documents/Phases/Two/Vision Phase Two.pdf
Labels: documentation
